### ISSUE TITLE
Example of how VCS settings work

### ISSUE THREAD

**Issue by itanex** [glen-84/vscode-sass-lint#1]
The following settings sound great but I cannot seem to get them to work. Can you provide examples of what values could be and how they would resolve? The config file path setting is not clear as to if it handles only the path or what kinds of paths are possible. The relative to config, is that the config of the workspace or the user? I am currently on a Mac, though I am sure Windows examples would be welcome by the community as well.
- sasslint.configFile - A .sass-lint.yml file to use/fallback to if no config file is found in the current project.
- sasslint.resolvePathsRelativeToConfig - This option allows you to choose to resolve file paths relative to your
  config file rather than relative to the root of your currently open project.

**Comment by glen-84** [comment]
Hi Bryan,

The two settings are not related:
- `sasslint.configFile` is the path to a `.sass-lint.yml` file. I'm currently using an absolute path like `D:/path/to/.sass-lint.yml` (on Windows). I'm not sure what a relative path would load relative to. I can investigate, if you need this.
- `sasslint.resolvePathsRelativeToConfig` is for the resolution of the paths specified in the `files` section of a `.sass-lint.yml` file.

Are you wanting to reference a config file outside of your workspace, and if so, are you able to use an absolute path?

**Comment by glen-84** [comment]
Closing. If you need any more information, let me know.
