### ISSUE TITLE
Failed to load sass-lint library when Sass Lint is installed by Yarn

### ISSUE THREAD

**Issue by Grawl** [glen-84/vscode-sass-lint#13]
I installed `sass-lint` by `yarn global add sass-lint` and can run it with `bash` and `fish` terminals, but `vscode-sass-lint` works only after `npm i -g sass-lint`.

**Comment by glen-84** [comment]
See https://github.com/Microsoft/vscode-eslint/issues/187

**Comment by glen-84** [comment]
v1.0.0 includes a `packageManager` setting that can be set to `yarn`.

Please confirm that it's working for you.
