### ISSUE TITLE
Include relative path not working

### ISSUE THREAD

**Issue by hotforfeature** [glen-84/vscode-sass-lint#14]
When I first saw this extension, I installed it an expected it to work with a globally installed `sass-lint` and a local `.sass-lint.yml` project file. The only prerequisite in the readme is "The extension requires that sass-lint is installed either locally or globally."

Linting does not occur in this setup, so I tried disabling the vscode built-in `scss.validate` and `css.validate` options to no avail.

Running `$ sass-lint` in my project root folder produces expected lint errors, yet there are no visible hints, warnings, or errors when viewing a `.scss` file in vscode.

The root repo has a separate readme discussing a server, but there's no "sass-lint-server" npm package or vscode extension. At this point, I'm not even sure if this extension is supposed to generate in-editor lint errors or if it is intended for something else.

**Comment by glen-84** [comment]
Hi Andrew,

> I installed it an expected it to work with a globally installed sass-lint and a local .sass-lint.yml project file.

It does (should).

> I'm not even sure if this extension is supposed to generate in-editor lint errors or if it is intended for something else.

It does (should).

----

Could you please provide some more information about your setup?

* OS version
* VS Code version
* Node.js version
* sass-lint version
* Extension configuration
* `.sass-lint.yml` configuration
* Location of `.sass-lint.yml` file in relation to the file being linted
* etc.

**Comment by hotforfeature** [comment]
- macOS Sierre 10.12.3
- Code 1.12.2
- node 6.9.5
- sass-lint 1.10.2
- Code User Settings
```json
{
    "css.validate": false,
    "scss.validate": false
}
```
- .sass-lint.yml
```yml
options:
  formatter: stylish
files:
  include: './src/**/*.scss'
rules:
  property-sort-order:
    - 2
    -
      order: concentric
      ignore-custom-properties: true
```
- yml is in root folder of project. Sass file is in `src/app/app.component.scss`, this is an Angular CLI project

**Comment by glen-84** [comment]
Can you try:

```yaml
files:
  include: 'src/**/*.scss'
```

Instead?

**Comment by hotforfeature** [comment]
Well that did it, never would have thought to try that. Did some research, and this may be linked to https://github.com/cowboy/node-globule/issues/31, though there hasn't been any activity on that in a while.

Updated the title to help future devs when searching
