### ISSUE TITLE
Support sass-lint module in project subdirectory

### ISSUE THREAD

**Issue by TrevorBurnham** [glen-84/vscode-sass-lint#16]
I have a project set up like this:

```
/my-project
  /styles-for-a
  /styles-for-b
```

Both `styles-for-a` and `styles-for-b` have a `.sass-lint.yml` and an installed sass-lint node module. However, trying to open a Sass file in either dir yields

```
Failed to load sass-lint library. Please install sass-lint in your workspace folder…
```

My project setup works as expected in Atom's [linter-sass-lint](https://github.com/AtomLinter/linter-sass-lint/). I'd suggest that the sass-lint node module should be resolved relative to each `.sass-lint.yml`, rather than at the workspace root.

**Comment by mtpultz** [comment]
With a lot of projects split into /client and /server with separate package.json it seems like the vscode plugin should use the files current working directory (cwd) to check for sass-lint then recursively check upwards for the node_modules folder, or include sass-lint so it doesn't have to be pulled in by the developer.  Either way should check for lint configuration based on the cwd.

**Comment by glen-84** [comment]
This should work in v1.0.0. Please confirm that it's working for you.
