### ISSUE TITLE
Error is displayed when sass-lint is not installed in current project

### ISSUE THREAD

**Issue by fgallardograzio** [glen-84/vscode-sass-lint#17]
When working on a project in which sass-lint is not being used, (so it's not installed as a local npm dev dependency), the extension will complain when settings are saved.

This is the error that's presented as a VS Code notification dialog:

> Failed to load sass-lint library. Please install sass-lint in your workspace folder using 'npm

IMO if sass-lint is not found in the current project, the extension should behave as if it was disabled.

I wouldn't mind this error (could even be helpful, actually) if VS Code would allow users to disable extensions globally and enable them on a per-workspace basis. Then users would just enable extensions like this only on projects that actually need them. ( https://github.com/Microsoft/vscode/issues/15611 )

Thanks!

**Comment by glen-84** [comment]
Hi @fgallardograzio,

You can disable the extension with `"sasslint.enable": false` in the workspace settings file, or disable it globally in your user settings and then enable it on a per-workspace basis.
