### ISSUE TITLE
Please add normal installation guide for vs code. 

### ISSUE THREAD

**Issue by antonpegov** [glen-84/vscode-sass-lint#20]
'sasslint.enable - Enable or disable linting.' - what should I do with that?

**Comment by glen-84** [comment]
... enable or disable linting. 😄 

The default is `true`.

`The extension requires that sass-lint is installed either locally or globally.` (from the README)

Is it not working for you?

**Comment by KaushalyaPradeep** [comment]
not working for me.
Config is  given below
I have `npm install -g sass-lint -g` but not working.
`  "sasslint.configFile": "",
"sasslint.enable": true,
"sasslint.nodePath": "",
"sasslint.packageManager": "npm",
"sasslint.resolvePathsRelativeToConfig": false,
 "sasslint.run": "onType",
 "sasslint.trace.server": "off",`
