### ISSUE TITLE
vscode-sass-lint: 'Cannot read property 'Symbol(Symbol.iterator)' of undefined' while validating

### ISSUE THREAD

**Issue by eugenePel** [glen-84/vscode-sass-lint#21]
Hello. I keep repeatedly getting the same VS Code error, when trying to enter something into my .scss files. 
The full text of the error is in the attachment. Linting doesn't work. Can you tell please, what could be an issue? Thanks.
![sass-lint-error](https://user-images.githubusercontent.com/28061379/33608864-8524d2ce-d9ce-11e7-82b7-a863a86b4321.jpg)

**Comment by mishac** [comment]
I've got the same issue.

Error message:
vscode-sass-lint: 'Cannot read property 'Symbol(Symbol.iterator)' of undefined' while validating: c:\\Users\\[FILENAME]  stacktrace: TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined

**Comment by glen-84** [comment]
Which version of VS Code are you using?

**Comment by mishac** [comment]
I'm on 1.18.1

Full info from "About" dialog, in case it's relevant:

> Version 1.18.1
> Commit 929bacba01ef658b873545e26034d1a8067445e9
> Date 2017-11-16T18:32:36.023Z
> Shell: 1.7.9
> Renderer: 58.03029.110
> Node: 7.9.0
> Architecture X64

**Comment by eugenePel** [comment]
![visual studio code version](https://user-images.githubusercontent.com/28061379/33623855-1da402f0-d9fb-11e7-85e5-78b412a80ffd.png)

**Comment by eugenePel** [comment]
![visual studio code version](https://user-images.githubusercontent.com/28061379/33624104-f11482c2-d9fb-11e7-9100-befbd265a66e.png)

**Comment by glen-84** [comment]
I've just released a new version (`1.0.1`). Please let me know if this fixes the issue.

I'm not really sure why `workspaceFolders` is `undefined` for you, as I wasn't able to reproduce the error.

**Comment by mishac** [comment]
That seems to have fixed it for me!

**Comment by eugenePel** [comment]
Error disappears and everything seems to work. Thank you for fixing it so fast!
