### ISSUE TITLE
[scss] ( expected when interpolation is used

### ISSUE THREAD

**Issue by Kovas** [glen-84/vscode-sass-lint#22]
Hello,

I get `[scss] ( expected` when interpolation is used for variable in media query:
```
    @media screen and #{breakpoint(medium)} and (min-height: 50em) {
        min-height: 100vh;
        padding: rem-calc(200 0);
    }
```
`#{breakpoint(medium)}` returns `(min-width: 40em)`, so there's no need for `(`.

Is there anything I can do about it?

**Comment by glen-84** [comment]
That's coming from the built-in SCSS validation.

You can disable it with:

```json
"scss.validate": false
```
(in your VS Code settings)

**Comment by Kovas** [comment]
My bad. Thanks :)
