### ISSUE TITLE
Global config file

### ISSUE THREAD

**Issue by morvy** [glen-84/vscode-sass-lint#24]
Could you please tell me how and where to put the _.sass-lint.yml_ so it is used globally in all projects? I would like to set indent size to 4 but I could only set it per project. Am I missing something?

**Comment by glen-84** [comment]
Hi @morvy,

You can use the `sasslint.configFile` setting in your user or workspace settings file.

e.g. (Windows)

```json
"sasslint.configFile": "D:/path/to/.sass-lint.yml"
```

If that's not working for you, I'll need more information, such as:

* OS version
* VS Code version
* Node.js version
* sass-lint version
* Extension configuration
* .sass-lint.yml configuration
* Location of .sass-lint.yml file in relation to the file being linted
* etc.
