### ISSUE TITLE
:not(:first-child()) causes an error

### ISSUE THREAD

**Issue by Morialkar** [glen-84/vscode-sass-lint#27]
While this selector is a valid CSS line, the sass-lint extension throws an error and doesn't check the rest of the file

**Comment by glen-84** [comment]
Hi Philippe,

You should probably remove the parentheses after `:first-child`.

Also please note that this extension just invokes [sass-lint](https://github.com/sasstools/sass-lint), so if it was a bug, in most cases it should be reported there.

Thanks.
