### ISSUE TITLE
sass-lint server causes 100% cpu load

### ISSUE THREAD

**Issue by c-emil** [glen-84/vscode-sass-lint#28]
I noticed that my MacBook Pro 15's (running on Mojave 10.14.2) vent was very loud so I checked Activity monitor and there was Code helper process running. So checked the PID and ran `ps aux | grep 1234` in terminal. The output was the following:

```bash
100.0  0.4  5126880  69648   ??  R    12:08PM   2:48.45 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Users/whatever/.vscode/extensions/glen-84.sass-lint-1.0.4/server/sass-lint-server.js --node-ipc --clientProcessId=32034
```

So it's coming from your extension. I have a lot of sass and scss files in my project, but at the same time, other extensions do not cause such issues and there's much more js files in the project and I have eslint enabled as well.

After disabling your plugin, the issue no longer appeared. Disabling is not a solution though because I need linter :)

**Comment by glen-84** [comment]
Hi Emil,

Could you please provide the following information?:

* VS Code version
* Node.js version
* sass-lint version (not this extension, the library itself)
* Local or global installation of sass-lint
* Extension configuration
* .sass-lint.yml configuration
* Location of .sass-lint.yml file in relation to the file being linted
* etc.

You can also enable tracing:

* Add `"sasslint.trace.server": "verbose"` to your settings
* Open the Output window
* Select `Sass Lint` from the drop-down menu

**Comment by c-emil** [comment]
Hi @glen-84, thanks for your quick reply and sorry for my late reply but for some reason I missed the email with your reply. In any case, I've tried reproducing the error once more so that I'm sure which project caused it (different projects, different sass-lints, and even different node versions) and I cannot reproduce it. I'll turn on the verbose trace and if it appears again, I'll let you know.

**Comment by glen-84** [comment]
Thanks for the update.

I'll close this issue for now. You're welcome to drop a message here if you need me to re-open it.
