### ISSUE TITLE
Not picking up configuration from project .sass-lint.yml file

### ISSUE THREAD

**Issue by IanOvenden** [glen-84/vscode-sass-lint#3]
Hi,

I've got a .sass-lint.yml file in place within our project for use within our asset build.  I've recently installed this plugin and should be able to point it to this file for the validation rules.  The plugin is running and throwing up errors but these do not reflect those rules in my config file.

Changes to this file also seem not to have any effect.  

I've tried specifying the sass-lint config file path directly in my package.json file, but that didn't work.  

I have also tried setting the plugin config option sasslint.configFile, but understand this is a fallback.

Am I missing something?  

Thanks.

**Comment by glen-84** [comment]
Hi Ian,

Please provide some additional information, such as:
- OS
- VS Code version
- Node.js version
- sass-lint version
- sass-lint installed locally or globally
- Location of `.sass-lint.yml` file within your project/workspace (at the root or deeper?)
- Location of sass/scss file that is showing the wrong messages (relative to the config file)
- etc.

Thanks.

**Comment by IanOvenden** [comment]
Sorry, I should have provided more info initially - I just wondered if I'd missed something simple.  Details below:

OS: **Windows 7 Enterprise**
VS Code version: **1.4.0**
Node.js version: **0.12.7**
sass-lint version: **1.8.2**
sass-lint installed locally or globally: **GLOBALLY**
Location of .sass-lint.yml file within your project/workspace (at the root or deeper?): **DEEPER - "\grunt\config.sass-lint.yml"**
Location of sass/scss file that is showing the wrong messages (relative to the config file) : **....\src\core\scss\widgets\my-sass-file.scss**

Thanks for your help.

Ian

**Comment by glen-84** [comment]
I assume it's `\grunt\config\.sass-lint.yml`?

In order for that to be picked up, it would need to be in a parent folder of the Sass file (which it isn't).

You should be able to use the `sasslint.configFile` option, something like:

``` json
"sasslint.configFile": "C:/path/to/grunt/config/.sass-lint.yml"
```

I'm not sure if relative paths work, and if they do, what they're relative to, but you can try that as well.

You may need to make a change to your Sass file to trigger a re-run of the linter with updated config (this used to work without that, but I think that this might have changed with the introduction of tabs).

**Comment by IanOvenden** [comment]
Ahhh, my bad - in our build process we are actually using **scss**-lint.  The .sass-lint.yml file is configured for that and not **sass**-lint.  Apologies for wasting your time.

**Comment by glen-84** [comment]
No worries. =)
