### ISSUE TITLE
JSON .sasslintrc config file support ?

### ISSUE THREAD

**Issue by capsudo** [glen-84/vscode-sass-lint#30]
I use a JSON config file such as the one provided in the docs : https://github.com/sasstools/sass-lint/blob/develop/docs/.sasslintrc

I have set option `sasslint.configFile` to `.sasslintrc` in settings, however vscode does not seem to use it at all. I do have lint warnings/errors showing on scss file but it does not seem to be affceted by rule changes in `.sasslintrc`.

Is JSON config file supported by this extension ?

- vscode-sass-lint 1.0.4
- VS code: 1.31.1
- OS: Linux x64 4.15.0-45-generic

**Comment by capsudo** [comment]
My bad, it does work, I had to reload vscode to get it working (see issue #31).

**Comment by glen-84** [comment]
Reopening.

`.sasslintrc` files are not yet (fully) supported.

**Comment by glen-84** [comment]
Support for `.sasslintrc` configuration files has been added in `v1.0.5`.
