### ISSUE TITLE
[Feature-Request] update linting on config rule change without vscode reload

### ISSUE THREAD

**Issue by capsudo** [glen-84/vscode-sass-lint#31]
Currently if I edit the rules in my `sass-lint.yml` file the linting is not updated. I need to reload vscode window (command palette > reload window).

- vscode-sass-lint 1.0.4
- VS code: 1.31.1
- OS: Linux x64 4.15.0-45-generic

**Comment by glen-84** [comment]
Hi @monkeydri,

Just to confirm, are you using:

1. `sass-lint.yml` or
2. `.sass-lint.yml` or
3. `.sasslintrc`

?

**Comment by capsudo** [comment]
I am using `.sasslintrc` but had the same behaviour when using `sass-lint.yml`.

**Comment by glen-84** [comment]
* `.sasslintrc` is not yet fully supported by this extension (#30)
* `sass-lint.yml` is not a valid configuration file name, please try `.sass-lint.yml`

**Comment by capsudo** [comment]
I confirm it works when using `.sass-lint.yml` (setting `sasslint.configFile` settings entry to it or leaving it empty) : linting in editor is updated on rule change without VScode window needing to be reloaded.

> sass-lint.yml is not a valid configuration file name, please try .sass-lint.yml

I initially tried `sass-lint.ym` over `.sass-lint.ym` because this is the name of the file used in sass-lint docs : https://raw.githubusercontent.com/sasstools/sass-lint/develop/docs/sass-lint.yml

**Comment by glen-84** [comment]
Thanks for the confirmation.
