### ISSUE TITLE
config file location and rule resolution

### ISSUE THREAD

**Issue by joneff** [glen-84/vscode-sass-lint#35]
Can the extension support editor-config-style file location (https://editorconfig.org/#file-location) and rule resolution e.g. when linting files to look in the same dir; then in the parent one and so on and so forth, until it reaches the root of the project?

**Comment by glen-84** [comment]
It should do that already – is it not working for you?

**Comment by joneff** [comment]
Here is a screenshot of a very simple setup:

* indentation of 4 spaces, it reports it as 2; should be error, reports it as warning;
* quotes double, reports it as single; should be error, reports it as warning;

![image](https://user-images.githubusercontent.com/8048/59246925-73be2d80-8c26-11e9-9e57-35d4a4a1126c.png)

Also, can there be a hint / tree structure where the rules come from?

**Comment by glen-84** [comment]
The config file name should be `.sass-lint.yml` or `.sasslintrc` (note the leading period).

**Comment by joneff** [comment]
Worked like a charm. Closing this issue.
