### ISSUE TITLE
Doesn't see sass-lint

### ISSUE THREAD

**Issue by xahon** [glen-84/vscode-sass-lint#38]
> [Info  - 1:27:29 PM] Failed to load the sass-lint library for the document "/home/ilya/dev/Drom/TestTask/src/assets/styles/style.sass"
> 
> To use sass-lint in this workspace, install it using "npm install sass-lint", or globally using "npm install -g sass-lint".
> 
> You need to reopen the workspace after installing sass-lint.

```
~ : which sass-lint 
/usr/local/bin/sass-lint
```

restart vscode...

the same output as above

**Comment by glen-84** [comment]
That directory doesn't look right. What do you get when running `npm root -g`?

**Comment by xahon** [comment]
@glen-84 `/usr/lib/node_modules`

**Comment by xahon** [comment]
I've installed it via `npm i -g sass-lint` and it works
Previously I made install via `yarn global add sass-lint`

Need for another issue on this for yarn installation
