### ISSUE TITLE
Doesn't see sass-lint installed globally via yarn

### ISSUE THREAD

**Issue by xahon** [glen-84/vscode-sass-lint#39]
Related: https://github.com/glen-84/vscode-sass-lint/issues/38

**Comment by glen-84** [comment]
Did you set `sasslint.packageManager` to `"yarn"`?

**Comment by xahon** [comment]
@glen-84 no

**Comment by glen-84** [comment]
Does it work if you do that?

**Comment by xahon** [comment]
@glen-84 no

> [Info  - 5:52:43 PM] Failed to load the sass-lint library for the document "/home/ilya/dev/Drom/TestTask/src/sharedStyles/Inputs.scss"
> 
> To use sass-lint in this workspace, install it using "yarn add sass-lint", or globally using "yarn global add sass-lint".
> 
> You need to reopen the workspace after installing sass-lint.

**Comment by glen-84** [comment]
Did you close and reopen VS Code after making the change?

**Comment by xahon** [comment]
@glen-84 yes, it has no effect

**Comment by glen-84** [comment]
Can you please run:

* `yarn global dir`
* `yarn global list sass-lint`

**Comment by xahon** [comment]
@glen-84 
> ~ : yarn global dir
> /home/ilya/.config/yarn/global
--------------------
> ~ : yarn global list sass-lint
> yarn global v1.19.1
> info "tsd@0.9.0" has binaries:
>    - tsd
> info "typings@2.1.1" has binaries:
>    - typings
> Done in 0.35s.

**Comment by glen-84** [comment]
You should see:

```
info "sass-lint@1.13.1" has binaries:
   - sass-lint
```

Did you run `yarn global add sass-lint`?
