### ISSUE TITLE
Question: Where can we disable particular rules?

### ISSUE THREAD

**Issue by xahon** [glen-84/vscode-sass-lint#40]
For example, I want to disable `Class '.optionsList' should be written in lowercase with hyphenssass-lint(class-name-format)` rule, because I use css-modules extension and want to be persistent in code-style

**Comment by glen-84** [comment]
> Please refer to the sass-lint documentation for how to configure the linting rules.

https://github.com/sasstools/sass-lint#configuring

i.e. create a `.sass-lint.yml` or `.sasslintrc` file in your project.

If you want to merge the default rules, see [this document](https://github.com/sasstools/sass-lint/blob/master/docs/options/merge-default-rules.md).

**Comment by glen-84** [comment]
Actually `merge-default-rules` is `true` by default, so you can just do:

```yaml
rules:
    class-name-format: 0
```

**Comment by xahon** [comment]
is there an auto-fixer?

**Comment by glen-84** [comment]
[No](https://github.com/sasstools/sass-lint/issues/904).
