### ISSUE TITLE
Cant lint CSS custom properties if property-sort-order is enabled

### ISSUE THREAD

**Issue by summers173** [glen-84/vscode-sass-lint#42]
Using the basic example from [https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties) : 

`element {
  --main-bg-color: brown;
}`

I got the following error: 

`vscode-sass-lint: 'Cannot read property 'first' of null' while validating: X.scss stacktrace: TypeError: Cannot read property 'first' of null at C:\Users\X\AppData\Roaming\npm\node_modules\sass-lint\lib\rules\property-sort-order.js:108:27 at Node.forEach `

This only happens if on 'sass-lint.yml' the 'property-sort-order' is set to 1.

Thanks for your time and great work on this extension.

Best regards

**Comment by glen-84** [comment]
That is an error from sass-lint itself, not from this extension.

See https://github.com/sasstools/sass-lint/issues/1161, https://github.com/sasstools/sass-lint/issues/1224.

Note: sass-lint (the library) is no longer maintained, so I would recommend that you switch to [stylelint](https://stylelint.io/) instead.

**Comment by summers173** [comment]
Thanks so much for the advice, your time, and great work on the extension.

I'll check stylelint, best regards.
