### ISSUE TITLE
How do you set the sasslint.configFile to the root/home on Mac OS?

### ISSUE THREAD

**Issue by dallanlee** [glen-84/vscode-sass-lint#7]
I have tried several options to point to my configuration file at the root of my Mac OS. The VS Code extension CSSComb uses the root location and so I want to put my .sass-lint.yml file there as well. In my settings I have tried:

`"sasslint.configFile": "$HOME/.sass-lint.yml"`
`"sasslint.configFile": "~/.sass-lint.yml"`
`"sasslint.configFile": "/.sass-lint.yml"`
`"sasslint.configFile": "$HOME"`
`"sasslint.configFile": "~"`

The instructions provided are not very clear to me. Help would really be appreciated.

**Comment by glen-84** [comment]
On Windows I'm using an absolute path like `D:/path/to/.sass-lint.yml`, so I would assume that on a Mac it would be `/.sass-lint.yml`.

Do you have any `.sass-lint.yml` files inside the project or a parent folder of the file being linted? If so, it would take precedence.

Unfortunately I don't have access to a Mac, so it's not easy for me to test this.

**Comment by dallanlee** [comment]
Thank you, @glen-84. This made me realize I should do `/Users/dallanlee/.sass-lint.yml` which did work!
